[2025-10-12T20:48:34.825+0000] {processor.py:157} INFO - Started process (PID=76) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:48:34.836+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:48:34.865+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:48:34.862+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:48:35.141+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:48:35.102+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:48:35.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:48:35.267+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.478 seconds
[2025-10-12T20:49:05.378+0000] {processor.py:157} INFO - Started process (PID=131) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:49:05.380+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:49:05.384+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:49:05.383+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:49:05.432+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:49:05.421+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:49:05.435+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:49:05.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.092 seconds
[2025-10-12T20:49:36.048+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:49:36.049+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:49:36.054+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:49:36.053+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:49:36.114+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:49:36.107+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:49:36.117+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:49:36.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.126 seconds
[2025-10-12T20:50:06.257+0000] {processor.py:157} INFO - Started process (PID=243) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:50:06.259+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:50:06.262+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:50:06.261+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:50:06.326+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:50:06.309+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:50:06.330+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:50:06.358+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.104 seconds
[2025-10-12T20:50:36.455+0000] {processor.py:157} INFO - Started process (PID=300) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:50:36.456+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:50:36.459+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:50:36.459+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:50:36.509+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:50:36.502+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:50:36.512+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:50:36.543+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.094 seconds
[2025-10-12T20:51:07.090+0000] {processor.py:157} INFO - Started process (PID=356) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:51:07.092+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:51:07.095+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:51:07.094+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:51:07.132+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:51:07.124+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:51:07.135+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:51:07.159+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.074 seconds
[2025-10-12T20:51:37.458+0000] {processor.py:157} INFO - Started process (PID=412) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:51:37.459+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:51:37.464+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:51:37.463+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:51:37.513+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:51:37.505+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:51:37.515+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:51:37.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.087 seconds
[2025-10-12T20:52:07.964+0000] {processor.py:157} INFO - Started process (PID=468) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:52:07.971+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:52:07.981+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:52:07.980+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:52:08.189+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:52:08.161+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:52:08.205+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:52:08.280+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.334 seconds
[2025-10-12T20:52:39.125+0000] {processor.py:157} INFO - Started process (PID=524) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:52:39.128+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:52:39.135+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:52:39.134+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:52:39.226+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:52:39.206+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:52:39.232+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:52:39.286+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.173 seconds
[2025-10-12T20:53:10.400+0000] {processor.py:157} INFO - Started process (PID=578) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:53:10.408+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:53:10.430+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:53:10.428+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:53:10.627+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:53:10.607+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:53:10.633+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:53:10.681+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.314 seconds
[2025-10-12T20:53:40.793+0000] {processor.py:157} INFO - Started process (PID=634) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:53:40.795+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:53:40.802+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:53:40.802+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:53:40.955+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:53:40.929+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:53:40.963+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:53:41.041+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.258 seconds
[2025-10-12T20:54:11.260+0000] {processor.py:157} INFO - Started process (PID=690) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:54:11.262+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:54:11.279+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:54:11.269+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:54:11.410+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:54:11.391+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:54:11.416+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:54:11.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.213 seconds
[2025-10-12T20:54:41.914+0000] {processor.py:157} INFO - Started process (PID=746) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:54:41.917+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:54:41.924+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:54:41.923+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:54:42.070+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:54:42.049+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:54:42.077+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:54:42.117+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.214 seconds
[2025-10-12T20:55:12.258+0000] {processor.py:157} INFO - Started process (PID=802) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:55:12.264+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:55:12.275+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:55:12.274+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:55:12.434+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:55:12.402+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:55:12.445+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:55:12.517+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.279 seconds
[2025-10-12T20:55:42.742+0000] {processor.py:157} INFO - Started process (PID=859) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:55:42.745+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:55:42.751+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:55:42.750+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:55:42.868+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:55:42.842+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:55:42.875+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:55:42.938+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.205 seconds
[2025-10-12T20:58:36.189+0000] {processor.py:157} INFO - Started process (PID=77) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:58:36.193+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:58:36.207+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:58:36.206+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:58:36.325+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:58:36.303+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:58:36.331+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:58:36.447+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.278 seconds
[2025-10-12T20:59:06.569+0000] {processor.py:157} INFO - Started process (PID=133) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:59:06.572+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:59:06.589+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:59:06.581+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:59:06.703+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:59:06.678+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:59:06.709+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:59:06.760+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.204 seconds
[2025-10-12T20:59:37.047+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T20:59:37.061+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T20:59:37.091+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:59:37.083+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:59:37.502+0000] {logging_mixin.py:151} INFO - [2025-10-12T20:59:37.402+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T20:59:37.534+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T20:59:37.751+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.771 seconds
[2025-10-12T21:00:08.084+0000] {processor.py:157} INFO - Started process (PID=245) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:00:08.092+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:00:08.111+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:00:08.108+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:00:08.381+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:00:08.321+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:00:08.398+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:00:08.518+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.465 seconds
[2025-10-12T21:00:38.884+0000] {processor.py:157} INFO - Started process (PID=301) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:00:38.892+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:00:38.918+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:00:38.911+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:00:39.266+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:00:39.196+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:00:39.273+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:00:39.324+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.467 seconds
[2025-10-12T21:01:10.286+0000] {processor.py:157} INFO - Started process (PID=358) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:01:10.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:01:10.303+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:01:10.302+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:01:10.408+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:01:10.387+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:01:10.415+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:01:10.495+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.229 seconds
[2025-10-12T21:01:40.649+0000] {processor.py:157} INFO - Started process (PID=414) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:01:40.651+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:01:40.656+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:01:40.655+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:01:40.766+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:01:40.737+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:01:40.771+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:01:40.825+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.188 seconds
[2025-10-12T21:02:11.317+0000] {processor.py:157} INFO - Started process (PID=470) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:02:11.321+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:02:11.333+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:02:11.331+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:02:11.493+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:02:11.450+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:02:11.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:02:11.557+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.253 seconds
[2025-10-12T21:02:41.913+0000] {processor.py:157} INFO - Started process (PID=525) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:02:41.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:02:41.937+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:02:41.935+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:02:42.336+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:02:42.158+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:02:42.353+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:02:42.451+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.561 seconds
[2025-10-12T21:03:12.753+0000] {processor.py:157} INFO - Started process (PID=581) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:03:12.761+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:03:12.777+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:03:12.775+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:03:12.964+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:03:12.910+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:03:12.981+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:03:13.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.369 seconds
[2025-10-12T21:03:43.772+0000] {processor.py:157} INFO - Started process (PID=637) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:03:43.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:03:43.783+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:03:43.782+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:03:43.941+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:03:43.893+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:03:43.958+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:03:44.075+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.310 seconds
[2025-10-12T21:04:14.240+0000] {processor.py:157} INFO - Started process (PID=692) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:04:14.244+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:04:14.254+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:04:14.253+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:04:14.375+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:04:14.353+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:04:14.382+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:04:14.431+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.207 seconds
[2025-10-12T21:04:45.016+0000] {processor.py:157} INFO - Started process (PID=748) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:04:45.019+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:04:45.032+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:04:45.030+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:04:45.128+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:04:45.109+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:04:45.135+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:04:45.207+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.206 seconds
[2025-10-12T21:05:15.502+0000] {processor.py:157} INFO - Started process (PID=804) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:05:15.505+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:05:15.515+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:05:15.514+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:05:15.662+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:05:15.635+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:05:15.669+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:05:15.722+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.233 seconds
[2025-10-12T21:05:46.688+0000] {processor.py:157} INFO - Started process (PID=861) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:05:46.693+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:05:46.713+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:05:46.710+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:05:46.973+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:05:46.923+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:05:46.990+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:05:47.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.436 seconds
[2025-10-12T21:06:17.760+0000] {processor.py:157} INFO - Started process (PID=918) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:06:17.762+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:06:17.771+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:06:17.770+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:06:17.885+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:06:17.854+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:06:17.893+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:06:17.961+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.209 seconds
[2025-10-12T21:06:48.125+0000] {processor.py:157} INFO - Started process (PID=975) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:06:48.131+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:06:48.148+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:06:48.146+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:06:48.409+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:06:48.353+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:06:48.425+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:06:48.543+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.437 seconds
[2025-10-12T21:07:19.182+0000] {processor.py:157} INFO - Started process (PID=1031) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:07:19.186+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:07:19.202+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:07:19.200+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:07:19.375+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:07:19.354+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:07:19.381+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:07:19.430+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.261 seconds
[2025-10-12T21:07:50.344+0000] {processor.py:157} INFO - Started process (PID=1087) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:07:50.350+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:07:50.371+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:07:50.369+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:07:50.675+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:07:50.625+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:07:50.692+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:07:50.815+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.492 seconds
[2025-10-12T21:08:21.037+0000] {processor.py:157} INFO - Started process (PID=1143) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:08:21.044+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:08:21.065+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:08:21.063+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:08:21.324+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:08:21.271+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:08:21.341+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:08:21.458+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.453 seconds
[2025-10-12T21:08:52.007+0000] {processor.py:157} INFO - Started process (PID=1199) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:08:52.014+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:08:52.031+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:08:52.029+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:08:52.192+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:08:52.171+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:08:52.199+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:08:52.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.291 seconds
[2025-10-12T21:09:22.787+0000] {processor.py:157} INFO - Started process (PID=1252) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:09:22.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:09:22.804+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:09:22.802+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:09:22.945+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:09:22.915+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:09:22.954+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:09:23.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.280 seconds
[2025-10-12T21:09:54.109+0000] {processor.py:157} INFO - Started process (PID=1309) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:09:54.117+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:09:54.133+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:09:54.132+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:09:54.406+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:09:54.350+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:09:54.424+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:09:54.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.461 seconds
[2025-10-12T21:10:25.282+0000] {processor.py:157} INFO - Started process (PID=1365) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:10:25.289+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:10:25.307+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:10:25.305+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:10:25.578+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:10:25.522+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:10:25.594+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:10:25.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.451 seconds
[2025-10-12T21:10:56.460+0000] {processor.py:157} INFO - Started process (PID=1421) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:10:56.468+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:10:56.494+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:10:56.492+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:10:56.985+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:10:56.919+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:10:57.001+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:10:57.116+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.677 seconds
[2025-10-12T21:11:27.997+0000] {processor.py:157} INFO - Started process (PID=1478) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:11:28.000+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:11:28.008+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:11:28.007+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:11:28.148+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:11:28.118+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:11:28.163+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:11:28.260+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.274 seconds
[2025-10-12T21:12:46.842+0000] {processor.py:157} INFO - Started process (PID=1488) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:12:46.844+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:12:46.852+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:12:46.851+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:12:47.077+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:12:47.031+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:12:47.085+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:12:47.461+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.640 seconds
[2025-10-12T21:22:18.823+0000] {processor.py:157} INFO - Started process (PID=1546) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:22:18.827+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:22:18.830+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:22:18.829+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:22:18.973+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:22:18.942+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:22:18.982+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:22:19.047+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.234 seconds
[2025-10-12T21:22:50.309+0000] {processor.py:157} INFO - Started process (PID=1596) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:22:50.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:22:50.316+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:22:50.315+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:22:50.442+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:22:50.410+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:22:50.449+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:22:50.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.223 seconds
[2025-10-12T21:23:20.749+0000] {processor.py:157} INFO - Started process (PID=1652) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:23:20.754+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:23:20.759+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:23:20.758+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:23:21.033+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:23:20.972+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:23:21.049+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:23:21.169+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.437 seconds
[2025-10-12T21:24:15.464+0000] {processor.py:157} INFO - Started process (PID=1683) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:24:15.471+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:24:15.478+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:24:15.473+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:24:15.660+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:24:15.595+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:24:15.678+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:24:17.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 2.485 seconds
[2025-10-12T21:24:48.430+0000] {processor.py:157} INFO - Started process (PID=1737) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:24:48.437+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:24:48.444+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:24:48.442+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:24:48.728+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:24:48.662+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:24:48.746+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:24:48.821+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.425 seconds
[2025-10-12T21:25:19.290+0000] {processor.py:157} INFO - Started process (PID=1793) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:25:19.296+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:25:19.303+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:25:19.300+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:25:19.485+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:25:19.452+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:25:19.494+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:25:19.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.296 seconds
[2025-10-12T21:25:50.159+0000] {processor.py:157} INFO - Started process (PID=1849) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:25:50.162+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:25:50.168+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:25:50.167+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:25:50.299+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:25:50.272+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:25:50.308+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:25:50.873+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.727 seconds
[2025-10-12T21:26:21.235+0000] {processor.py:157} INFO - Started process (PID=1905) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:26:21.242+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:26:21.248+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:26:21.246+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:26:21.533+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:26:21.456+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:26:21.552+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:26:21.669+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.455 seconds
[2025-10-12T21:26:55.878+0000] {processor.py:157} INFO - Started process (PID=1948) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:26:55.882+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:26:55.886+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:26:55.885+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:26:56.033+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:26:56.005+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:26:56.041+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:26:56.110+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.244 seconds
[2025-10-12T21:27:26.264+0000] {processor.py:157} INFO - Started process (PID=2003) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:27:26.267+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:27:26.269+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:27:26.269+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:27:26.369+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:27:26.349+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:27:26.374+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:27:26.422+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.167 seconds
[2025-10-12T21:31:35.038+0000] {processor.py:157} INFO - Started process (PID=2029) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:31:35.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:31:35.055+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:31:35.048+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:31:35.195+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:31:35.174+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:31:35.201+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:31:35.248+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.241 seconds
[2025-10-12T21:32:05.414+0000] {processor.py:157} INFO - Started process (PID=2086) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:32:05.416+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:32:05.419+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:32:05.418+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:32:05.542+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:32:05.518+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:32:05.549+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:32:05.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.244 seconds
[2025-10-12T21:32:35.871+0000] {processor.py:157} INFO - Started process (PID=2142) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:32:35.876+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:32:35.883+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:32:35.881+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:32:36.168+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:32:36.093+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:32:36.185+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:32:36.323+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.473 seconds
[2025-10-12T21:33:06.654+0000] {processor.py:157} INFO - Started process (PID=2199) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:33:06.656+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:33:06.662+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:33:06.658+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:33:06.746+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:33:06.726+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:33:06.752+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:33:06.814+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.173 seconds
[2025-10-12T21:33:37.613+0000] {processor.py:157} INFO - Started process (PID=2255) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:33:37.621+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:33:37.633+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:33:37.625+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:33:37.765+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:33:37.742+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:33:37.771+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:33:37.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.240 seconds
[2025-10-12T21:34:08.630+0000] {processor.py:157} INFO - Started process (PID=2311) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:34:08.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:34:08.639+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:34:08.637+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:34:08.743+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:34:08.720+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:34:08.750+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:34:08.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.188 seconds
[2025-10-12T21:34:39.117+0000] {processor.py:157} INFO - Started process (PID=2367) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:34:39.124+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:34:39.130+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:34:39.128+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:34:39.423+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:34:39.364+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:34:39.440+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:34:39.565+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.470 seconds
[2025-10-12T21:35:10.029+0000] {processor.py:157} INFO - Started process (PID=2423) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:35:10.035+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:35:10.042+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:35:10.040+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:35:10.337+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:35:10.278+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:35:10.353+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:35:10.481+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.476 seconds
[2025-10-12T21:35:41.642+0000] {processor.py:157} INFO - Started process (PID=2472) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:35:41.647+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:35:41.652+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:35:41.649+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:35:41.845+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:35:41.792+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:35:41.883+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:35:47.742+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 6.117 seconds
[2025-10-12T21:36:18.332+0000] {processor.py:157} INFO - Started process (PID=2526) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:36:18.335+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:36:18.338+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:36:18.337+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:36:18.461+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:36:18.427+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:36:18.470+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:36:18.544+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.224 seconds
[2025-10-12T21:36:49.480+0000] {processor.py:157} INFO - Started process (PID=2589) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:36:49.496+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:36:49.504+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:36:49.503+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:36:49.652+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:36:49.631+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:36:49.661+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:36:49.711+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.251 seconds
[2025-10-12T21:37:20.625+0000] {processor.py:157} INFO - Started process (PID=2645) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:37:20.635+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:37:20.640+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:37:20.638+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:37:20.761+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:37:20.734+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:37:20.768+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:37:20.821+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.235 seconds
[2025-10-12T21:37:50.975+0000] {processor.py:157} INFO - Started process (PID=2694) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:37:50.978+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:37:50.983+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:37:50.980+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:37:51.127+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:37:51.091+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:37:51.135+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:37:51.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.341 seconds
[2025-10-12T21:38:21.974+0000] {processor.py:157} INFO - Started process (PID=2750) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:38:21.981+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:38:21.992+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:38:21.990+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:38:22.112+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:38:22.088+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:38:22.118+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:38:22.179+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.224 seconds
[2025-10-12T21:38:52.778+0000] {processor.py:157} INFO - Started process (PID=2806) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:38:52.785+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:38:52.795+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:38:52.792+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:38:52.918+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:38:52.891+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:38:52.926+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:38:52.991+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.245 seconds
[2025-10-12T21:39:23.445+0000] {processor.py:157} INFO - Started process (PID=2862) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:39:23.449+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:39:23.454+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:39:23.451+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:39:23.577+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:39:23.552+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:39:23.583+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:39:23.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.215 seconds
[2025-10-12T21:39:54.723+0000] {processor.py:157} INFO - Started process (PID=2925) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:39:54.727+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:39:54.734+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:39:54.730+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:39:54.877+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:39:54.842+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:39:54.885+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:39:54.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.246 seconds
[2025-10-12T21:40:25.383+0000] {processor.py:157} INFO - Started process (PID=2981) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:40:25.387+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:40:25.393+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:40:25.392+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:40:25.516+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:40:25.491+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:40:25.521+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:40:25.581+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.210 seconds
[2025-10-12T21:40:55.838+0000] {processor.py:157} INFO - Started process (PID=3037) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:40:55.845+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:40:55.850+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:40:55.848+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:40:56.139+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:40:56.070+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:40:56.160+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:40:56.272+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.451 seconds
[2025-10-12T21:41:26.515+0000] {processor.py:157} INFO - Started process (PID=3093) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:41:26.522+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:41:26.530+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:41:26.526+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:41:26.828+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:41:26.780+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:41:26.836+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:41:26.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.433 seconds
[2025-10-12T21:41:57.450+0000] {processor.py:157} INFO - Started process (PID=3142) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:41:57.455+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:41:57.468+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:41:57.458+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:41:57.610+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:41:57.579+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:41:57.620+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:41:57.842+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.412 seconds
[2025-10-12T21:42:28.367+0000] {processor.py:157} INFO - Started process (PID=3198) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:42:28.374+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:42:28.381+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:42:28.379+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:42:28.566+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:42:28.546+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:42:28.571+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:42:28.628+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.282 seconds
[2025-10-12T21:42:59.206+0000] {processor.py:157} INFO - Started process (PID=3254) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:42:59.211+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:42:59.216+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:42:59.215+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:42:59.328+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:42:59.309+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:42:59.335+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:42:59.388+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.242 seconds
[2025-10-12T21:43:30.253+0000] {processor.py:157} INFO - Started process (PID=3317) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:43:30.256+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:43:30.259+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:43:30.258+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:43:30.397+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:43:30.366+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:43:30.405+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:43:30.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.225 seconds
[2025-10-12T21:44:00.844+0000] {processor.py:157} INFO - Started process (PID=3366) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:44:00.851+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:44:00.860+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:44:00.854+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:44:01.040+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:44:00.993+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:44:01.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:44:11.081+0000] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 842, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 625, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-10-12T21:44:41.869+0000] {processor.py:157} INFO - Started process (PID=3422) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:44:41.877+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:44:41.885+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:44:41.882+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:44:42.086+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:44:42.045+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:44:42.093+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:44:42.161+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.329 seconds
[2025-10-12T21:45:12.452+0000] {processor.py:157} INFO - Started process (PID=3477) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:45:12.458+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:45:12.464+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:45:12.463+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:45:12.734+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:45:12.669+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:45:12.749+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:45:12.888+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.456 seconds
[2025-10-12T21:45:44.059+0000] {processor.py:157} INFO - Started process (PID=3540) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:45:44.066+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:45:44.077+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:45:44.071+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:45:44.260+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:45:44.221+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:45:44.270+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:45:44.340+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.313 seconds
[2025-10-12T21:46:14.846+0000] {processor.py:157} INFO - Started process (PID=3595) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:46:14.851+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:46:14.858+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:46:14.853+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:46:14.987+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:46:14.958+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:46:14.994+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:46:15.122+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.291 seconds
[2025-10-12T21:46:45.712+0000] {processor.py:157} INFO - Started process (PID=3652) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:46:45.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:46:45.730+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:46:45.728+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:46:45.849+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:46:45.829+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:46:45.855+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:46:45.904+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.221 seconds
[2025-10-12T21:47:16.843+0000] {processor.py:157} INFO - Started process (PID=3708) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:47:16.849+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:47:16.860+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:47:16.858+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:47:17.073+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:47:17.052+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:47:17.079+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:47:17.123+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.304 seconds
[2025-10-12T21:47:47.531+0000] {processor.py:157} INFO - Started process (PID=3765) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:47:47.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:47:47.538+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:47:47.536+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:47:47.636+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:47:47.613+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:47:47.644+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:47:47.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.209 seconds
[2025-10-12T21:48:18.640+0000] {processor.py:157} INFO - Started process (PID=3821) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:48:18.645+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:48:18.649+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:48:18.648+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:48:18.767+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:48:18.743+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:48:18.778+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:48:18.835+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.207 seconds
[2025-10-12T21:48:49.372+0000] {processor.py:157} INFO - Started process (PID=3877) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:48:49.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:48:49.384+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:48:49.383+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:48:49.641+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:48:49.591+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:48:49.651+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:48:49.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.382 seconds
[2025-10-12T21:49:20.312+0000] {processor.py:157} INFO - Started process (PID=3933) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:49:20.318+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:49:20.323+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:49:20.321+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:49:20.454+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:49:20.421+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:49:20.466+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:49:20.529+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.237 seconds
[2025-10-12T21:49:59.413+0000] {processor.py:157} INFO - Started process (PID=3978) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:49:59.417+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:49:59.421+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:49:59.420+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:49:59.506+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:49:59.483+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:49:59.512+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:49:59.561+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.161 seconds
[2025-10-12T21:50:29.760+0000] {processor.py:157} INFO - Started process (PID=4034) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:50:29.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:50:29.765+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:50:29.765+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:50:29.886+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:50:29.863+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:50:29.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:50:29.942+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.190 seconds
[2025-10-12T21:51:00.322+0000] {processor.py:157} INFO - Started process (PID=4089) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:51:00.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:51:00.329+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:51:00.329+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:51:00.491+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:51:00.437+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:51:00.508+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:51:00.626+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.314 seconds
[2025-10-12T21:51:31.267+0000] {processor.py:157} INFO - Started process (PID=4146) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:51:31.271+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:51:31.275+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:51:31.274+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:51:31.408+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:51:31.383+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:51:31.413+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:51:31.471+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.216 seconds
[2025-10-12T21:52:02.473+0000] {processor.py:157} INFO - Started process (PID=4195) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:52:02.477+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:52:02.484+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:52:02.480+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:52:02.615+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:52:02.585+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:52:02.623+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:52:02.765+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.308 seconds
[2025-10-12T21:52:33.029+0000] {processor.py:157} INFO - Started process (PID=4250) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:52:33.036+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:52:33.042+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:52:33.040+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:52:33.307+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:52:33.248+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:52:33.324+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:52:33.445+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.438 seconds
[2025-10-12T21:53:03.724+0000] {processor.py:157} INFO - Started process (PID=4304) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:53:03.731+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:53:03.739+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:53:03.736+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:53:04.025+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:53:03.960+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:53:04.035+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:53:04.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.406 seconds
[2025-10-12T21:53:34.512+0000] {processor.py:157} INFO - Started process (PID=4360) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:53:34.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:53:34.523+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:53:34.520+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:53:34.672+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:53:34.645+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:53:34.681+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:53:34.791+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.296 seconds
[2025-10-12T21:54:05.051+0000] {processor.py:157} INFO - Started process (PID=4417) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:54:05.058+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:54:05.064+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:54:05.063+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:54:05.333+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:54:05.269+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:54:05.342+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:54:05.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.406 seconds
[2025-10-12T21:54:35.771+0000] {processor.py:157} INFO - Started process (PID=4473) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:54:35.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:54:35.785+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:54:35.783+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:54:36.091+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:54:36.017+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:54:36.098+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:54:36.169+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.421 seconds
[2025-10-12T21:55:06.905+0000] {processor.py:157} INFO - Started process (PID=4530) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:55:06.912+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:55:06.919+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:55:06.916+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:55:07.176+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:55:07.120+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:55:07.191+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:55:07.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.421 seconds
[2025-10-12T21:55:37.999+0000] {processor.py:157} INFO - Started process (PID=4586) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:55:38.018+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:55:38.032+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:55:38.021+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:55:38.355+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:55:38.253+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:55:38.381+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:55:47.544+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 9.572 seconds
[2025-10-12T21:56:17.773+0000] {processor.py:157} INFO - Started process (PID=4640) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:56:17.776+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:56:17.779+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:56:17.778+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:56:17.865+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:56:17.846+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:56:17.872+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:56:17.923+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.161 seconds
[2025-10-12T21:56:48.211+0000] {processor.py:157} INFO - Started process (PID=4696) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:56:48.214+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:56:48.217+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:56:48.216+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:56:48.405+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:56:48.342+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:56:48.421+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:56:48.577+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.375 seconds
[2025-10-12T21:57:19.231+0000] {processor.py:157} INFO - Started process (PID=4752) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:57:19.238+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:57:19.243+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:57:19.240+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:57:19.373+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:57:19.345+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:57:19.380+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:57:19.506+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.288 seconds
[2025-10-12T21:57:49.755+0000] {processor.py:157} INFO - Started process (PID=4808) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:57:49.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:57:49.770+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:57:49.767+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:57:49.944+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:57:49.915+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:57:49.951+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:57:50.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.377 seconds
[2025-10-12T21:58:20.860+0000] {processor.py:157} INFO - Started process (PID=4869) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:58:20.888+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:58:20.892+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:58:20.891+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:58:21.204+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:58:21.179+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:58:21.211+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:58:21.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.449 seconds
[2025-10-12T21:58:51.682+0000] {processor.py:157} INFO - Started process (PID=4926) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:58:51.689+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:58:51.696+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:58:51.693+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:58:51.972+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:58:51.913+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:58:51.989+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:58:52.173+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.516 seconds
[2025-10-12T21:59:22.603+0000] {processor.py:157} INFO - Started process (PID=4975) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:59:22.606+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:59:22.610+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:59:22.609+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:59:22.758+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:59:22.730+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:59:22.765+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:59:23.103+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.514 seconds
[2025-10-12T21:59:53.560+0000] {processor.py:157} INFO - Started process (PID=5032) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T21:59:53.567+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T21:59:53.573+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:59:53.571+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:59:53.883+0000] {logging_mixin.py:151} INFO - [2025-10-12T21:59:53.839+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T21:59:53.895+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T21:59:54.035+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.495 seconds
[2025-10-12T22:00:24.555+0000] {processor.py:157} INFO - Started process (PID=5088) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:00:24.561+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:00:24.568+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:00:24.566+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:00:24.839+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:00:24.771+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:00:24.855+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:00:24.975+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.445 seconds
[2025-10-12T22:00:56.854+0000] {processor.py:157} INFO - Started process (PID=5144) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:00:56.857+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:00:56.860+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:00:56.859+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:00:56.959+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:00:56.932+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:00:56.968+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:00:57.269+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.457 seconds
[2025-10-12T22:01:27.502+0000] {processor.py:157} INFO - Started process (PID=5200) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:01:27.505+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:01:27.508+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:01:27.507+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:01:27.611+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:01:27.588+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:01:27.618+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:01:27.669+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.179 seconds
[2025-10-12T22:01:58.134+0000] {processor.py:157} INFO - Started process (PID=5253) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:01:58.138+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:01:58.142+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:01:58.141+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:01:58.381+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:01:58.311+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:01:58.388+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:01:58.470+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.348 seconds
[2025-10-12T22:02:28.597+0000] {processor.py:157} INFO - Started process (PID=5310) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:02:28.599+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:02:28.602+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:02:28.601+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:02:28.732+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:02:28.707+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:02:28.740+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:02:28.794+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.207 seconds
[2025-10-12T22:02:59.063+0000] {processor.py:157} INFO - Started process (PID=5365) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:02:59.066+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:02:59.070+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:02:59.069+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:02:59.184+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:02:59.161+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:02:59.191+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:02:59.775+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.731 seconds
[2025-10-12T22:03:30.567+0000] {processor.py:157} INFO - Started process (PID=5421) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:03:30.574+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:03:30.581+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:03:30.579+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:03:30.852+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:03:30.791+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:03:30.868+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:03:30.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.440 seconds
[2025-10-12T22:04:01.381+0000] {processor.py:157} INFO - Started process (PID=5477) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:04:01.384+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:04:01.388+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:04:01.387+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:04:01.519+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:04:01.491+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:04:01.527+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:04:01.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.219 seconds
[2025-10-12T22:04:32.041+0000] {processor.py:157} INFO - Started process (PID=5533) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:04:32.047+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:04:32.054+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:04:32.052+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:04:32.324+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:04:32.265+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:04:32.340+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:04:32.466+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.449 seconds
[2025-10-12T22:05:02.747+0000] {processor.py:157} INFO - Started process (PID=5589) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:05:02.751+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:05:02.755+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:05:02.754+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:05:02.888+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:05:02.860+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:05:02.900+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:05:02.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.247 seconds
[2025-10-12T22:05:33.545+0000] {processor.py:157} INFO - Started process (PID=5645) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:05:33.551+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:05:33.558+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:05:33.556+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:05:33.817+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:05:33.759+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:05:33.832+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:05:33.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.428 seconds
[2025-10-12T22:06:07.897+0000] {processor.py:157} INFO - Started process (PID=5694) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:06:07.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:06:07.902+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:06:07.901+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:06:08.009+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:06:07.985+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:06:08.017+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:06:08.084+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.199 seconds
[2025-10-12T22:06:38.355+0000] {processor.py:157} INFO - Started process (PID=5746) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:06:38.359+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:06:38.362+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:06:38.361+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:06:38.477+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:06:38.452+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:06:38.485+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:06:38.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.191 seconds
[2025-10-12T22:07:09.623+0000] {processor.py:157} INFO - Started process (PID=5799) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:07:09.626+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:07:09.629+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:07:09.628+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:07:09.734+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:07:09.712+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:07:09.740+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:07:09.800+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.186 seconds
[2025-10-12T22:07:40.848+0000] {processor.py:157} INFO - Started process (PID=5851) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:07:40.850+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:07:40.854+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:07:40.853+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:07:40.981+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:07:40.958+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:07:40.987+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:07:41.051+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.214 seconds
[2025-10-12T22:08:11.276+0000] {processor.py:157} INFO - Started process (PID=5899) to work on /opt/airflow/dags/chromedriver.py
[2025-10-12T22:08:11.280+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver.py for tasks to queue
[2025-10-12T22:08:11.283+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:08:11.282+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:08:11.426+0000] {logging_mixin.py:151} INFO - [2025-10-12T22:08:11.394+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2025-10-12T22:08:11.434+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver.py
[2025-10-12T22:08:11.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver.py took 0.325 seconds
