[2025-10-16T17:23:59.955+0000] {processor.py:157} INFO - Started process (PID=74) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:23:59.967+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:23:59.993+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:23:59.993+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:24:00.381+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:24:00.327+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:24:00.388+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:24:00.503+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.566 seconds
[2025-10-16T17:24:52.058+0000] {processor.py:157} INFO - Started process (PID=141) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:24:52.066+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:24:52.109+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:24:52.108+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:24:52.397+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:24:52.376+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:24:52.401+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:24:52.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.542 seconds
[2025-10-16T17:25:25.202+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:25:25.206+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:25:25.234+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:25:25.233+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:25:25.536+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:25:25.461+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:25:25.555+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:25:25.646+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.488 seconds
[2025-10-16T17:25:56.765+0000] {processor.py:157} INFO - Started process (PID=257) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:25:56.768+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:25:56.776+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:25:56.776+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:25:56.897+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:25:56.884+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:25:56.901+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:25:57.013+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.259 seconds
[2025-10-16T17:26:27.656+0000] {processor.py:157} INFO - Started process (PID=314) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:26:27.662+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:26:27.678+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:26:27.677+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:26:27.861+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:26:27.834+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:26:27.871+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:26:28.024+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.388 seconds
[2025-10-16T17:26:58.424+0000] {processor.py:157} INFO - Started process (PID=373) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:26:58.428+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:26:58.436+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:26:58.435+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:26:58.514+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:26:58.500+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:26:58.517+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:26:58.584+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.171 seconds
[2025-10-16T17:27:29.097+0000] {processor.py:157} INFO - Started process (PID=432) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:27:29.102+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:27:29.114+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:27:29.113+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:27:29.222+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:27:29.209+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:27:29.226+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:27:29.296+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.213 seconds
[2025-10-16T17:28:00.129+0000] {processor.py:157} INFO - Started process (PID=491) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:28:00.133+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:28:00.156+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:28:00.155+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:28:00.240+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:28:00.228+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:28:00.244+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:28:00.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.193 seconds
[2025-10-16T17:28:30.622+0000] {processor.py:157} INFO - Started process (PID=550) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:28:30.626+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:28:30.636+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:28:30.635+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:28:30.717+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:28:30.707+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:28:30.720+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:28:30.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.158 seconds
[2025-10-16T17:29:01.215+0000] {processor.py:157} INFO - Started process (PID=609) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:29:01.219+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:29:01.227+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:29:01.227+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:29:01.376+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:29:01.321+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:29:01.380+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:29:02.870+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 1.668 seconds
[2025-10-16T17:29:33.148+0000] {processor.py:157} INFO - Started process (PID=668) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:29:33.152+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:29:33.166+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:29:33.165+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:29:33.242+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:29:33.230+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:29:33.244+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:29:33.286+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.156 seconds
[2025-10-16T17:30:03.869+0000] {processor.py:157} INFO - Started process (PID=727) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:30:03.880+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:30:03.924+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:30:03.923+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:30:04.029+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:30:04.020+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:30:04.033+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:30:04.340+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.544 seconds
[2025-10-16T17:30:35.314+0000] {processor.py:157} INFO - Started process (PID=786) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:30:35.318+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:30:35.327+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:30:35.327+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:30:35.400+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:30:35.391+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:30:35.403+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:30:35.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.152 seconds
[2025-10-16T17:31:05.609+0000] {processor.py:157} INFO - Started process (PID=845) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:31:05.620+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:31:05.630+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:31:05.629+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:31:05.731+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:31:05.718+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:31:05.735+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:31:05.838+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.247 seconds
[2025-10-16T17:31:35.986+0000] {processor.py:157} INFO - Started process (PID=905) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:31:35.989+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:31:35.996+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:31:35.995+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:31:36.081+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:31:36.072+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:31:36.083+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:31:36.136+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.159 seconds
[2025-10-16T17:32:06.971+0000] {processor.py:157} INFO - Started process (PID=964) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:32:06.977+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:32:06.991+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:32:06.990+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:32:07.159+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:32:07.147+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:32:07.163+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:32:07.243+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.298 seconds
[2025-10-16T17:32:37.673+0000] {processor.py:157} INFO - Started process (PID=1023) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:32:37.681+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:32:37.692+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:32:37.691+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:32:37.789+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:32:37.778+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:32:37.793+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:32:37.847+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.208 seconds
[2025-10-16T17:33:08.745+0000] {processor.py:157} INFO - Started process (PID=1082) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:33:08.760+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:33:08.768+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:33:08.767+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:33:08.919+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:33:08.906+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:33:08.923+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:33:08.980+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.253 seconds
[2025-10-16T17:33:39.960+0000] {processor.py:157} INFO - Started process (PID=1141) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:33:39.962+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:33:39.974+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:33:39.970+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:33:40.063+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:33:40.054+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:33:40.066+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:33:40.130+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.185 seconds
[2025-10-16T17:34:10.885+0000] {processor.py:157} INFO - Started process (PID=1201) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:34:10.889+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:34:10.899+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:34:10.898+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:34:11.028+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:34:11.015+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:34:11.033+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:34:11.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.215 seconds
[2025-10-16T17:34:41.553+0000] {processor.py:157} INFO - Started process (PID=1261) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:34:41.556+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:34:41.564+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:34:41.564+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:34:41.671+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:34:41.659+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:34:41.675+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:34:41.724+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.191 seconds
[2025-10-16T17:35:12.205+0000] {processor.py:157} INFO - Started process (PID=1320) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:35:12.209+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:35:12.216+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:35:12.215+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:35:12.349+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:35:12.333+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:35:12.354+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:35:12.414+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.222 seconds
[2025-10-16T17:35:42.589+0000] {processor.py:157} INFO - Started process (PID=1379) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:35:42.592+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:35:42.600+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:35:42.599+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:35:43.035+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:35:42.925+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:35:43.045+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:35:43.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.560 seconds
[2025-10-16T17:36:13.442+0000] {processor.py:157} INFO - Started process (PID=1442) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:36:13.446+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:36:13.457+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:36:13.456+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:36:13.566+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:36:13.555+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:36:13.569+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:36:13.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.192 seconds
[2025-10-16T17:36:44.474+0000] {processor.py:157} INFO - Started process (PID=1502) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:36:44.479+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:36:44.493+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:36:44.492+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:36:44.709+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:36:44.685+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:36:44.717+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:36:44.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.350 seconds
[2025-10-16T17:37:15.548+0000] {processor.py:157} INFO - Started process (PID=1562) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:37:15.550+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:37:15.556+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:37:15.555+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:37:15.649+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:37:15.637+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:37:15.652+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:37:15.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.164 seconds
[2025-10-16T17:37:46.166+0000] {processor.py:157} INFO - Started process (PID=1621) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:37:46.169+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:37:46.175+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:37:46.175+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:37:46.298+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:37:46.283+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:37:46.305+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:37:46.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.265 seconds
[2025-10-16T17:38:17.345+0000] {processor.py:157} INFO - Started process (PID=1680) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:38:17.347+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:38:17.353+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:38:17.353+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:38:17.465+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:38:17.451+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:38:17.469+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:38:17.531+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.198 seconds
[2025-10-16T17:38:47.693+0000] {processor.py:157} INFO - Started process (PID=1737) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:38:47.696+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:38:47.706+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:38:47.704+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:38:47.878+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:38:47.855+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:38:47.886+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:38:47.986+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.306 seconds
[2025-10-16T17:39:20.463+0000] {processor.py:157} INFO - Started process (PID=1794) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:39:20.467+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:39:20.483+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:39:20.482+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:39:20.667+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:39:20.645+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:39:20.674+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:39:20.753+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.329 seconds
[2025-10-16T17:39:51.646+0000] {processor.py:157} INFO - Started process (PID=1853) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:39:51.649+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:39:51.656+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:39:51.655+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:39:51.752+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:39:51.741+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:39:51.755+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:39:51.828+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.191 seconds
[2025-10-16T17:40:21.991+0000] {processor.py:157} INFO - Started process (PID=1911) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:40:21.993+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:40:21.999+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:40:21.999+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:40:22.113+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:40:22.097+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:40:22.118+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:40:22.204+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.222 seconds
[2025-10-16T17:40:52.580+0000] {processor.py:157} INFO - Started process (PID=1967) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:40:52.588+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:40:52.607+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:40:52.605+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:40:52.761+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:40:52.744+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:40:52.767+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:40:52.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.301 seconds
[2025-10-16T17:41:23.761+0000] {processor.py:157} INFO - Started process (PID=2026) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:41:23.770+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:41:23.799+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:41:23.797+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:41:23.925+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:41:23.913+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:41:23.930+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:41:23.983+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.248 seconds
[2025-10-16T17:41:54.616+0000] {processor.py:157} INFO - Started process (PID=2085) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:41:54.618+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:41:54.624+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:41:54.623+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:41:54.820+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:41:54.757+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:41:54.824+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:41:54.870+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.262 seconds
[2025-10-16T17:42:25.286+0000] {processor.py:157} INFO - Started process (PID=2144) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:42:25.292+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:42:25.311+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:42:25.309+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:42:25.546+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:42:25.535+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:42:25.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:42:25.592+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.327 seconds
[2025-10-16T17:42:55.817+0000] {processor.py:157} INFO - Started process (PID=2203) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:42:55.820+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:42:55.827+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:42:55.826+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:42:55.914+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:42:55.903+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:42:55.917+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:42:55.972+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.164 seconds
[2025-10-16T17:43:26.148+0000] {processor.py:157} INFO - Started process (PID=2263) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:43:26.151+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:43:26.159+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:43:26.157+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:43:26.286+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:43:26.273+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:43:26.291+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:43:26.351+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.212 seconds
[2025-10-16T17:43:56.805+0000] {processor.py:157} INFO - Started process (PID=2322) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:43:56.808+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:43:56.816+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:43:56.816+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:43:56.946+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:43:56.933+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:43:56.951+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:43:57.008+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.212 seconds
[2025-10-16T17:44:27.208+0000] {processor.py:157} INFO - Started process (PID=2381) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:44:27.213+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:44:27.228+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:44:27.226+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:44:27.439+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:44:27.416+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:44:27.446+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:44:27.560+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.370 seconds
[2025-10-16T17:44:58.247+0000] {processor.py:157} INFO - Started process (PID=2440) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:44:58.253+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:44:58.279+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:44:58.277+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:44:58.477+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:44:58.458+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:44:58.484+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:44:58.556+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.344 seconds
[2025-10-16T17:45:28.837+0000] {processor.py:157} INFO - Started process (PID=2501) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:45:28.842+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:45:28.856+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:45:28.855+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:45:29.222+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:45:29.193+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:45:29.232+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:45:29.331+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.512 seconds
[2025-10-16T17:45:59.542+0000] {processor.py:157} INFO - Started process (PID=2560) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:45:59.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:45:59.554+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:45:59.553+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:45:59.651+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:45:59.639+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:45:59.654+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:45:59.722+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.190 seconds
[2025-10-16T17:46:30.263+0000] {processor.py:157} INFO - Started process (PID=2617) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:46:30.266+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:46:30.274+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:46:30.273+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:46:30.373+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:46:30.361+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:46:30.382+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:46:30.481+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.230 seconds
[2025-10-16T17:51:36.839+0000] {processor.py:157} INFO - Started process (PID=84) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:51:36.844+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:51:36.858+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:51:36.856+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:51:36.968+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:51:36.956+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:51:36.974+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:51:37.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.263 seconds
[2025-10-16T17:52:08.060+0000] {processor.py:157} INFO - Started process (PID=142) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:52:08.068+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:52:08.093+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:52:08.092+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:52:08.449+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:52:08.371+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:52:08.486+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:52:08.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.550 seconds
[2025-10-16T17:52:39.096+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:52:39.099+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:52:39.106+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:52:39.105+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:52:39.209+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:52:39.196+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:52:39.213+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:52:39.273+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.186 seconds
[2025-10-16T17:53:10.204+0000] {processor.py:157} INFO - Started process (PID=260) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:53:10.208+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:53:10.218+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:53:10.217+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:53:10.291+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:53:10.282+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:53:10.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:53:10.340+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.150 seconds
[2025-10-16T17:53:40.728+0000] {processor.py:157} INFO - Started process (PID=319) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:53:40.731+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:53:40.738+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:53:40.737+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:53:40.841+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:53:40.830+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:53:40.844+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:53:40.906+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.186 seconds
[2025-10-16T17:54:11.409+0000] {processor.py:157} INFO - Started process (PID=376) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:54:11.411+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:54:11.418+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:54:11.417+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:54:11.755+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:54:11.732+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:54:11.766+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:54:12.065+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.667 seconds
[2025-10-16T17:54:42.185+0000] {processor.py:157} INFO - Started process (PID=435) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:54:42.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:54:42.195+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:54:42.194+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:54:42.279+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:54:42.268+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:54:42.283+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:54:42.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.163 seconds
[2025-10-16T17:55:13.992+0000] {processor.py:157} INFO - Started process (PID=495) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:55:13.996+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:55:14.004+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:55:14.003+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:55:14.110+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:55:14.097+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:55:14.115+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:55:14.175+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.193 seconds
[2025-10-16T17:55:44.856+0000] {processor.py:157} INFO - Started process (PID=554) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:55:44.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:55:44.867+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:55:44.866+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:55:44.949+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:55:44.939+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:55:44.954+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:55:45.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.164 seconds
[2025-10-16T17:56:16.048+0000] {processor.py:157} INFO - Started process (PID=609) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:56:16.051+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:56:16.059+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:56:16.058+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:56:16.162+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:56:16.151+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:56:16.166+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:56:16.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.207 seconds
[2025-10-16T17:56:49.489+0000] {processor.py:157} INFO - Started process (PID=660) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:56:49.492+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:56:49.501+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:56:49.500+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:56:49.588+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:56:49.571+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:56:49.591+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:56:49.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.160 seconds
[2025-10-16T17:57:20.105+0000] {processor.py:157} INFO - Started process (PID=718) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:57:20.109+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:57:20.116+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:57:20.115+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:57:20.216+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:57:20.205+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:57:20.220+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:57:20.284+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.189 seconds
[2025-10-16T17:57:51.054+0000] {processor.py:157} INFO - Started process (PID=775) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:57:51.058+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:57:51.067+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:57:51.066+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:57:51.192+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:57:51.180+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:57:51.196+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:57:51.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.207 seconds
[2025-10-16T17:58:21.737+0000] {processor.py:157} INFO - Started process (PID=833) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:58:21.740+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:58:21.747+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:58:21.746+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:58:21.846+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:58:21.834+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:58:21.850+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:58:21.902+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.172 seconds
[2025-10-16T17:58:52.852+0000] {processor.py:157} INFO - Started process (PID=891) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:58:52.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:58:52.863+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:58:52.862+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:58:52.972+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:58:52.962+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:58:52.975+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:58:53.024+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.182 seconds
[2025-10-16T17:59:23.687+0000] {processor.py:157} INFO - Started process (PID=948) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:59:23.690+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:59:23.698+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:59:23.698+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:59:23.836+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:59:23.819+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:59:23.843+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:59:23.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.242 seconds
[2025-10-16T17:59:54.902+0000] {processor.py:157} INFO - Started process (PID=1007) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:59:54.907+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T17:59:54.926+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:59:54.925+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:59:55.066+0000] {logging_mixin.py:151} INFO - [2025-10-16T17:59:55.049+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T17:59:55.077+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T17:59:55.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.279 seconds
[2025-10-16T18:00:25.689+0000] {processor.py:157} INFO - Started process (PID=1066) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:00:25.691+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T18:00:25.703+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:00:25.702+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:00:25.775+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:00:25.765+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T18:00:25.778+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:00:25.831+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.151 seconds
[2025-10-16T18:00:56.346+0000] {processor.py:157} INFO - Started process (PID=1125) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:00:56.348+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T18:00:56.356+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:00:56.355+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:00:56.467+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:00:56.448+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T18:00:56.474+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:00:56.595+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.258 seconds
[2025-10-16T18:01:27.348+0000] {processor.py:157} INFO - Started process (PID=1184) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:01:27.351+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T18:01:27.360+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:01:27.359+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:01:27.441+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:01:27.430+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T18:01:27.445+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:01:27.504+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.169 seconds
[2025-10-16T18:02:11.291+0000] {processor.py:157} INFO - Started process (PID=1205) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:02:11.294+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T18:02:11.301+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:02:11.300+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:02:11.373+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:02:11.364+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T18:02:11.376+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:02:11.425+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.146 seconds
[2025-10-16T18:02:42.387+0000] {processor.py:157} INFO - Started process (PID=1264) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:02:42.391+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T18:02:42.397+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:02:42.396+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:02:42.476+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:02:42.467+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T18:02:42.479+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:02:42.527+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.158 seconds
[2025-10-16T18:03:12.952+0000] {processor.py:157} INFO - Started process (PID=1321) to work on /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:03:12.956+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/chromedriver_v2.py for tasks to queue
[2025-10-16T18:03:12.964+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:03:12.963+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:03:13.068+0000] {logging_mixin.py:151} INFO - [2025-10-16T18:03:13.057+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/chromedriver_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/chromedriver_v2.py", line 12, in <module>
    from py_files.get_v2 import  StockResults
  File "/opt/airflow/dags/py_files/get_v2.py", line 34
    def __init__(self):
    ^
IndentationError: unexpected indent
[2025-10-16T18:03:13.073+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/chromedriver_v2.py
[2025-10-16T18:03:13.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/chromedriver_v2.py took 0.238 seconds
